// Code generated by wit-bindgen-go. DO NOT EDIT.

package sync

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
	"unsafe"
)

// RecShape is used for storage in variant or result types.
type RecShape struct {
	shape [unsafe.Sizeof(Rec{})]byte
}

func lower_RecNested(v RecNested) (f0 *uint8, f1 uint32) {
	f0, f1 = cm.LowerString(v.Foo)
	return
}

func lower_Rec(v Rec) (f0 *uint8, f1 uint32) {
	f0, f1 = lower_RecNested(v.Nested)
	return
}

func lower_TupleU8U8(v [2]uint8) (f0 uint32, f1 uint32) {
	f0 = (uint32)(v[0])
	f1 = (uint32)(v[1])
	return
}
